baseurl:       /gitwebpage
auto:          true
permalink:     pretty

title:         RoyHE
 

paginate:      5

pygments:      false
markdown:      rdiscount

author:
    name:      RoyHE
    weibo:  	http://weibo.com/u/1583427910
    gmail:     hry1225@gmail.com
    designer:  http://www.philipithomas.com/

description:   I am what I am
